verison: "3.1"
services:
    db:
    image: "mongo:latest"
    environment:
        - MONGO_INITDB_ROOT_USERNAME=root
        - MONGO_INITDB_ROOT_PASSWORD=password
        - MONGO_INITDB_DATABASE=app
    port:
        - "27017:27017"
    volumes:
        - "db:/data/db"
