.PHONY: seeds

test: 
	go test -v ./...

start:
	go run .

seeds:
	go run seeds/*

help:
	@echo "make test: run the tests"
	@echo "make start: run the application"
	@echo "make seeds: run the seeds"
	@echo "make help: show this message"